### ISSUE TITLE
Add `transposeKey` cell option to GridLY

### ISSUE THREAD

**Issue by uliska** [openlilylib/snippets#102]
I'm fine with 14c763021dfcd53733bb2147ca6a5adfdb84f688 and the rest of `gridly/development` and would be glad to merge this into `master` soon. However I have another idea I'd like to see implemented. I tried an implementation to create a Pull Request instead of a wish but failed on first attempt.

It would be nice to have another option for the `\with` clause: `transposeKey`. If that would be present it would be expected to be a single pitch and the music returned by ? \gridGetMusic`would be surrounded by a`\transpose <transposeKey> c { }` expression.

However, in order to be reliably usable this would have to take into account if the transposition changes between the different cells.

**Comment by Cecca** [comment]
OK, I'll try to implement this on a separate branch. So each cell should have its own transposition? To take into account if the transposition changes between different cells we can simply make the `\transpose` command surround each cell instead of the result of `gridGetMusic`.

**Comment by uliska** [comment]
The main point is having the possibility to use `\gridCompileCell` with the transposition, as it isn't possible to use the opening for that. When retrieving a range of cells with `\gridGetMusic` one would have access to enclosing the result in a `\transpose` clause but not for the single cell.

I think enclosing each cell individually would make sense, as this wouldn't hurt even if all cells are transposed the same.

**Comment by Cecca** [comment]
OK, once I have something ready I'll make a PR
