### ISSUE TITLE
idea: post-commit/post-fetch hook to update readme files

### ISSUE THREAD

**Issue by uliska** [openlilylib/snippets#11]
The Github web interface truncates the file names too much.

What about having the README.md files providing a TOC for the current folder?
Of course this isn't viable to do manually but has to be done by a script.

This script could check if there are changes to the file list in a directory and update the README if necessary (i.e. if files are added/removed/renamed).
It could also retrieve some meta infomation from the files' metadata.

I'm not sure if we find a suitable place to hook this script. Probably it would be best to run after fetching from Github.
It would then iterate over the repo, perform and commit its updates and push again. If someone else has done this before the script just wouldn't detect changes and wouldn't create a new commit.

What do you think?

**Comment by jan-warchol** [comment]
Sounds good, but i don't have time to implement it.  And actually, considering the desire of other Lily developers to keep all stuff in one place (and not on Github), we may yet have some structural changes that could make this obsolete.

Bottom line: would be nice, but i would drop it for now.

**Comment by uliska** [comment]
After reorganization we will actually have _one_ large directory with all files in it. This won't be conveniently browsable at Github so we will have to rely on a generated documentation script. I _think_ we will have that in the foreseeable future so we will just have to live with the current situation for a while.
