### ISSUE TITLE
edition-engraver not doing line breaks properly

### ISSUE THREAD

**Issue by ChrisTrahan** [openlilylib/snippets#116]
I have an SATB score with an interlude staff. I'm trying to use edition-engraver in order to remove \break statements from the music code. The score has parts where SA are singing and TB are not, as well as the reverse. No one sings during the interludes.

The line breaks work as expected when all staves are visible. However, it does not line break properly when I hide empty staves.

Any idea why?

**Comment by uliska** [comment]
Without code it's hard to tell.
But do you apply the editionmods to the Score context?

**Comment by ChrisTrahan** [comment]
Yes. I've included a \layout block as per jpvoigt's example.

Well, now when I go back to create a screenshot to illustrate what's happening, it's working. I do get error messages though.

```
programming error: could not find this grob's vertical axis group in the vertical alignment
continuing, cross finger
```

There's something in the code that's causing this. Any ideas?

**Comment by uliska** [comment]
Sorry, no idea ( I don't know that code at all). Maybe @jpvoigt does.

But there's a pull request dangling for some time now (sorry!) which rewrites the edition engraver partially. Maybe you should check this out (or wait for it to be merged) before we touch thecexudting version.

**Comment by ChrisTrahan** [comment]
I was getting this error before I started using edition-engraver so I think it's related to line breaks. I'm trying to remember what I did to get rid of the errors.

**Comment by davidnalesnik** [comment]
Is it related to this?

http://www.mail-archive.com/lilypond-user%40gnu.org/msg98697.html

David

**Comment by ChrisTrahan** [comment]
Yes, David, that's it. I should have kept a copy of the score with the \break statements in the score block.  I hadn't had time to go back and search for my forum post.

I'll try putting the breaks in edition-engraver in those same places.

Chris

**Comment by ChrisTrahan** [comment]
Hey David,

I was able to cut out enough code to make a tiny example and still get it
to fail. Would you take a look at this to see if you can figure out why I'm
getting the errors?

If you comment out the statements to remove empty staves in the \layout
block, it works fine but with them in it generates errors and strange
results.

Thanks,
Chris

**Comment by davidnalesnik** [comment]
Hi Chris,

My computing activities right now are limited to what I can accomplish
hunting and pecking with my left hand, so that pretty much rules out
anything other than answering simple questions.  I thought your problem was
related to shortening volta brackets and as such is a bug in the volta
engraver, something which I can't tackle.  possibly you can get more
assistance on -user.

Best,
David

**Comment by ChrisTrahan** [comment]
Thanks David.

Chris

**Comment by uliska** [comment]
@ChrisTrahan @davidnalesnik Is this related to the edition-engraver, respectively to openLilyLib at all?

If not please close the issue.
