### ISSUE TITLE
remove generalized-offsets?

### ISSUE THREAD

**Issue by jan-warchol** [openlilylib/snippets#13]
@davidnalesnik 
`\offset` was added to LilyPond itself, so i suppose it doesn't make sense keeping another version here?

**Comment by davidnalesnik** [comment]
On Fri, Oct 18, 2013 at 7:09 PM, Janek Warchoł notifications@github.comwrote:

> @davidnalesnik https://github.com/davidnalesnik
> \offset was added to LilyPond itself, so i suppose it doesn't make sense
> keeping another version here?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openlilylib/snippets/issues/13
> .

Hm.  Probably doesn't make much sense to downgrade it to 2.16...

**Comment by jan-warchol** [comment]
2013/10/19 davidnalesnik notifications@github.com

> Hm. Probably doesn't make much sense to downgrade it to 2.16...

Yes, i think that's not worth the effort.
