### ISSUE TITLE
Shouldn't lalily and edition engraver be placed somewhere else?

### ISSUE THREAD

**Issue by jan-warchol** [openlilylib/snippets#32]
@jpvoigt it seems to me that lalily should be placed in `templates`, and edition-engraver either in `templates` or in `input shorthands`.  The `general tools` folder is a bit confusing for me.  What do you think?

**Comment by jpvoigt** [comment]
Am 18.03.2014 09:24, schrieb Janek Warchoł:

> @jpvoigt https://github.com/jpvoigt it seems to me that lalily should
> be placed in |templates|, and edition-engraver either in |templates| or
> in |input shorthands|. The |general tools| folder is a bit confusing for
> me. What do you think?

I think you are right ... I will do so later today!

**Comment by jan-warchol** [comment]
great, thanks! :)

2014-03-18 9:49 GMT+01:00 jpvoigt notifications@github.com:
