### ISSUE TITLE
Rename the "snippets" repository?

### ISSUE THREAD

**Issue by uliska** [openlilylib/snippets#39]
I think we should rename the "snippets" repository (again), even if that requires some action for all users.

Two reasons:
1. I've always disliked the naming collision with the official LSR
2. Actually we encourage the use of this repository as an includable library and not as a repository for snippets to take from.

What do you think?

I don't think a rename would break actual scores. Usually it should be dealt with by changing stuff like the include path. And _if_ someone would rely on an explicit folder name (for example due to relative paths) he can still keep the name on the local disk.

I think the name should reflect the character as a library, but of course we already have the "openlilylib/" prefix which probably can't or shouldn't be touched. So suggestions are welcome.
- openlilylib/library
- openlilylib/oll
- openlilylib/oll-lib
- openlilylib/ollib
- openlilylib/somepoeticname???

**Comment by mcFrax** [comment]
openlilylib/rary ;)

What about openlilylib/openlilylib? First "openlilylib" isn't really part of the name, and it is lost when you clone the repo. It is common to have same organization and repository name, like git/git or django/django.

Btw, http://www.openlilylib.org/oll-lib/ still points to https://github.com/openlilylib/lilylib.

**Comment by uliska** [comment]
> What about openlilylib/openlilylib? openlilylib/ part isn't really part of the name, and it is lost when you clone the repo. It is common to have same organization and repository name, like git/git or django/django.

I think I'd be also fine with that. After all, openlilylib was the original name created for this repository idea, only later all the other repos were added.

> Btw, http://www.openlilylib.org/oll-lib/ still points to https://github.com/openlilylib/lilylib.

OK, thanks for the report, I'll update that once we have decided about the current issue

**Comment by jan-warchol** [comment]
I agree that the repo should be renamed, and i think Franek's right - openlilylib/openlilylib makes most sense :)

**Comment by nhthn** [comment]
My vote also goes for openlilylib/openlilylib.

**Comment by uliska** [comment]
Ok, then let's do that. What's the todo list? To make the change and offer enough information to all possible users?

**Comment by uliska** [comment]
According to the [GitHub help](https://help.github.com/articles/renaming-a-repository) renaming a repository doesn't break anything (clone, fetch, push will be redirected).

Therefore I will now rename the repository, write an email to lilypond-user and update the README with a notice

**Comment by uliska** [comment]
Fixed (and rewrote) http://openlilylib.org/library/
