### ISSUE TITLE
grob anchor debug script destroys layout on cross-staff elements

### ISSUE THREAD

**Issue by abelcheung** [openlilylib/snippets#44]
![bad-layout-grob-anchor](https://cloud.githubusercontent.com/assets/83110/3636157/4e08359c-0fa6-11e4-91be-03bb088d7c99.png)

Screenshot is illustrated by the following fragment:

``` lilypond
\include "display-grob-anchors.ily"

one = { s1 }
two = {
  \clef bass
  \override Beam.auto-knee-gap = ##f
  c8 d \change Staff="Staff1" e'' f''
  \override Beam.auto-knee-gap = 1
  gis'' fis'' \change Staff="Staff2" ees des |
}

\score {
%  \new StaffGroup <<
  \new StaffGroup \with { \printAnchors #'(SystemStartBracket Beam) } <<
    \new Staff = "Staff1" << \one >>
    \new Staff = "Staff2" << \two >>
  >>
}
```

Printing anchor of anything crossing staff would introduce a wide gap between staves, destroying the original layout. In this example, `SystemStartBracket`, `Beam` and `Stem` would have such effect, while `TimeSignature` `NoteHead` etc won't introduce problem (they are contained within single staff).

Same problem seem to exist with grob name displaying script.

**Comment by uliska** [comment]
Can you please check if this is the same for all LilyPond versions?

**Comment by abelcheung** [comment]
At least true for both current stable (2.18.2) and devel (2.19.10) versions. Hope I will have time for `git bisect` to trace its origin within these few days.

**Comment by abelcheung** [comment]
Time to let go, I haven't been spending any time on typesetting stuff for years.
