### ISSUE TITLE
README for doc-script

### ISSUE THREAD

**Issue by flaminghakama** [openlilylib/snippets#53]
In order that people other than Urs can help work on the doc-script that generates the HTML documentation for snippets, we need some kind of README file that explains how it works.

What is currently known (from email):

The oll.py contains the logic of parsing and managing the openlilylib files, while html.py contains the code to generate the HTML.

**Comment by uliska** [comment]
Before that makes sense it has to be reconsidered if the scripts shouldn't be redone completely. They were started for a previous attempt to restructure the library.

Probably much of it can be reused but I think we first should have a fundamental discussion about a library and API documentation system - which is part of the current approach for a new, integrated `openLilyLib`.

**Comment by uliska** [comment]
Moved to new issue #61
