### ISSUE TITLE
os-path: unbound variable `listcwd`

### ISSUE THREAD

**Issue by Cecca** [openlilylib/snippets#95]
Using the latest version on `master` (d4f36ae) I get the following error

```
lilypond -I /opt/openlilylib -I /opt/openlilylib/ly main.ly
GNU LilyPond 2.18.2
Elaborazione di «main.ly»
Analisi...

openLilyLib: library infrastructure successfully loaded.

/opt/openlilylib/ly/_internal/../_internal/utilities/os-path.scm:101:76: In expression (listcwd):
/opt/openlilylib/ly/_internal/../_internal/utilities/os-path.scm:101:76: Unbound variable: listcwd
```

Looks like listcwd is not defined. Maybe its definition is in a branch still to be merged?

**Comment by uliska** [comment]
No, these are calls to an obsolete function (they were copied from `scheme-lib/lalily/parser-location.scm` and not renamed) that have made it through the tests. Obviously I never executed this conditional ...
Please see if #96 fixes it for you.
